<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gos</string>
		<string>goose</string>
	</array>
	<key>name</key>
	<string>Goose</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>".*"</string>
			<key>name</key>
			<string>string.quoted.double.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'.*'</string>
			<key>name</key>
			<string>string.quoted.single.gos</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>string.interpolated.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\btrue\b)|(\bfalse\b)|[\+-]?\d+i?|\.\d+|e\d+</string>
			<key>name</key>
			<string>constant.numeric.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|default|func|interface|select|case|defer|go|map|struct|chan|else|goto|package|switch|const|fallthrough|if|range|type|continue|for|import|return|var)\b</string>
			<key>name</key>
			<string>keyword.control.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(uint8|uint16|uint32|uint64|int8|int16|int32|int64|float32|float64|complex64|complex128|byte|rune|int|uint|uintptr|string|nil)\b</string>
			<key>name</key>
			<string>keyword.other.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(main|struct|type)\b</string>
			<key>name</key>
			<string>entity.name.function.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\/\/.*$</string>
			<key>name</key>
			<string>comment.line.gos</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.regexp.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|:=|\;|\|\|&amp;&amp;|==|\!=|&lt;|&lt;=|&gt;|&gt;=|\+|-|\||\^|\*|/|%|&lt;&lt;|&gt;&gt;|&amp;|&amp;\^|\!|&lt;-</string>
			<key>name</key>
			<string>keyword.operator.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.\w+</string>
			<key>name</key>
			<string>entity.name.function.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\(\)\[\]\{\}]</string>
			<key>name</key>
			<string>constant.character.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\w+\d+\b</string>
			<key>name</key>
			<string>meta.gos</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gos</string>
	<key>uuid</key>
	<string>b14421e4-33ea-4045-b37d-eded78d9b836</string>
</dict>
</plist>
