<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gos</string>
		<string>goose</string>
	</array>
	<key>name</key>
	<string>Goose</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>".*"</string>
			<key>name</key>
			<string>string.quoted.double.gos</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>string.interpolated.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+|true|false</string>
			<key>name</key>
			<string>constant.numeric.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>package|for|if|import|var|const|func|case|switch</string>
			<key>name</key>
			<string>keyword.control.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>interface|int|float|string|int16|uint32|float64|complex128|byte|bool</string>
			<key>name</key>
			<string>keyword.other.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>main|struct|type</string>
			<key>name</key>
			<string>entity.name.function.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\/\/.*$</string>
			<key>name</key>
			<string>comment.line.gos</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.regexp.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\=|&lt;=|&gt;=|&lt;|&gt;|\*|\/</string>
			<key>name</key>
			<string>keyword.operator.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.\w+</string>
			<key>name</key>
			<string>entity.name.tag.gos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\(\)\[\]\{\}]</string>
			<key>name</key>
			<string>constant.character.gos</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gos</string>
	<key>uuid</key>
	<string>b14421e4-33ea-4045-b37d-eded78d9b836</string>
</dict>
</plist>
